#!/bin/bash
apt update
apt -y dist-upgrade
apt -y autoremove
apt clean
apt purge -y $(dpkg -l | awk '/^rc/ { print $2 }')

ulimit -HSn 32768

apt install curl -y

bash <(curl -s https://raw.githubusercontent.com/SageSBR/4master/main/rc-local.txt)

mkdir -p /backup/var/
wget https://raw.githubusercontent.com/SageSBR/4master/main/limpvar.sh;chmod +x /root/limpvar.sh

wget https://raw.githubusercontent.com/SageSBR/4master/main/mem.sh;chmod +x /root/mem.sh

wget https://raw.githubusercontent.com/SageSBR/4master/main/update.sh; chmod +x update.sh

curl -O http://c.myvestacp.com/vst-install-debian.sh

bash vst-install-debian.sh --force --nginx no --apache yes --phpfpm no --vsftpd no --proftpd yes --exim yes --dovecot yes --spamassassin yes --clamav no --named yes --iptables yes --fail2ban yes --softaculous yes --remi yes --quota no --mysql yes --postgresql no --hostname 4teambr.com --email 4teambrsg@gmail.com --port 26574 --password Sa@26071989
