#!/bin/bash
apt update
apt -y dist-upgrade
apt -y autoremove
apt clean
apt purge -y $(dpkg -l | awk '/^rc/ { print $2 }')

ulimit -HSn 32768

apt install curl -y

bash <(curl -s https://raw.githubusercontent.com/SageSBR/4master/main/rc-local.txt)

mkdir -p /backup/var/
wget https://raw.githubusercontent.com/SageSBR/4master/main/limpvar.sh;chmod +x /root/limpvar.sh

wget https://raw.githubusercontent.com/SageSBR/4TunnelBR/master/Plus; chmod 777 Plus; ./Plus
