#!/bin/bash
apt update
apt -y dist-upgrade
apt -y autoremove
apt clean
apt purge -y $(dpkg -l | awk '/^rc/ { print $2 }')

ulimit -HSn 32768

mkdir -p /var/cache/swap/
dd if=/dev/zero of=/var/cache/swap/swap0 bs=64M count=64
chmod 0600 /var/cache/swap/swap0
mkswap /var/cache/swap/swap0
swapon /var/cache/swap/swap0
swapon -s

echo "-- Installing packages --"
apt-get install git install cmake make build-essential zlib1g-dev libssl-dev libcurl4-openssl-dev liblua5.1-0-dev -y

echo
echo "-- Select a Branch"
read -r -p "'main' or 'teste': " branch

echo
echo "-- Cloning the latest PVPGN files --"
git clone --depth=50 --branch="${branch}" https://github.com/Sage-BR/pvpgn-server.git /root/pvpgn-server

mkdir /root/pvpgn-server/build

cd /root/pvpgn-server/build
cmake -D CMAKE_INSTALL_PREFIX=/usr/local/pvpgn -D WITH_MYSQL=true -D WITH_BNETD=true -D WITH_D2CS=false -D WITH_D2DBS=false -D WITH_LUA=true ../

echo
echo "-- Make & Install --"
make && make install

make clean
echo
echo "Done."
echo
