#!/bin/bash
apt update
apt -y dist-upgrade
apt -y autoremove
apt clean
apt purge -y $(dpkg -l | awk '/^rc/ { print $2 }')

ulimit -HSn 32768

mkdir -p /var/cache/swap/
dd if=/dev/zero of=/var/cache/swap/swap0 bs=64M count=64
chmod 0600 /var/cache/swap/swap0
mkswap /var/cache/swap/swap0
swapon /var/cache/swap/swap0
swapon -s

apt-get install git install cmake make build-essential zlib1g-dev libssl-dev libcurl4-openssl-dev liblua5.1-0-dev -y
cd /home
git clone https://github.com/pvpgn/pvpgn-server.git
cd /home/pvpgn-server
mkdir build
cd build
cmake -D CMAKE_INSTALL_PREFIX=/usr/local/pvpgn -D WITH_MYSQL=false -D WITH_LUA=true ../
make & make install
